[package]
authors = ["eV <ev@7pr.xyz>"]
edition = "2018"
name = "challenge-bypass-ristretto-ffi"
version = "0.1.0"

[dependencies]
rand = "0.5.5"
sha2 = "^0.7"


[dependencies.challenge-bypass-ristretto]
path = "/home/user/source/challenge-bypass-ristretto"

[lib]
crate-type = ["staticlib"]
name = "challenge_bypass_ristretto"
